spring:
  application:
    name : spring-batch
  profiles:
    active: local

  batch:
    job:
      name: executionJob


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;MODE=MYSQL
        username: sa
        password: 1234

---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 1548

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

