spring:
  application:
    name : spring-batch

  datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;MODE=MYSQL
        username: sa
        password: 1234
        h2:
          console:
            enabled: true
            path: /h2-console
